import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-5 border-4 border-yellow-500">
        <div
          id="left"
          className="col-span-2 col-start-1 border-4 border-red-500"
        >
          <h1>Klaudia Fecak</h1>
          <p>UI/UX Designer</p>
          <p>In design even the smallest iteration can change the outcome</p>
        </div>
        <div
          id="right"
          className="col-span-3 col-start-3 border-4 border-green-500"
        >
          <NavBar />
          <h1>Projects</h1>
        </div>
      </main>
    </>
  );
}
